---
- name: Reboot the server
  hosts: all
  become: true

  tasks:
    - name: Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
