---
- name: Open port a port for Firewalld
  hosts: all
  become: true

  tasks:
    - name: Open port
      ansible.posix.firewalld:
        port:  "{{ portnumber }}/{{ proto }}"
        permanent: yes
        state: enabled
      notify:
        - Restart firewalld

  handlers:
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
